---
source: tooling/nargo_cli/tests/execute.rs
expression: "&format!(\"success: {:?}\\nexit_code: {}\\n----- stdout -----\\n{}\\n----- stderr -----\\n{}\",\noutput.status.success(), output.status.code().unwrap_or(!0), stdout, stderr)"
---
success: false
exit_code: 1
----- stdout -----

----- stderr -----
bug: Assertion is always false
  ┌─ src/main.nr:3:25
  │
3 │     let _ = empty_input[0];
  │                         - As a result, the compiled circuit is ensured to fail. Other assertions may also fail during execution
  │
  = Call stack:
    1. src/main.nr:3:25

error: Assertion failed: Index out of bounds
  ┌─ src/main.nr:3:25
  │
3 │     let _ = empty_input[0];
  │                         -
  │
  = Call stack:
    1. src/main.nr:3:25

Failed assertion
